#kind: pipeline
#type: kubernetes
#name: Build Streamer App
#service_account_name: default
#
#metadata:
#  namespace: drone
#
#trigger:
#  branch:
#    - main
#  event:
#    exclude:
#      - pull_request
#
#steps:
#- name: set-tag-docker-streamer-service
#  image: python:3.9
#  environment:
#    DRONE: "true"
#  commands:
#  - echo -n app-v$DRONE_BUILD_NUMBER,app-latest > .tags
#  - cat .tags
#
#- name: docker-streamer-service
#  image: plugins/docker
#  settings:
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    repo: wildflowerschools/honeycomb-video-streamer
#    cache_from: wildflowerschools/honeycomb-video-streamer:app-latest

kind: pipeline
type: kubernetes
name: Build Streamer Prepare Service
service_account_name: default

metadata:
  namespace: drone

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
- name: dockerx prep
  image: thegeeklab/drone-docker
  privileged: true
  commands:
    - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  volumes:
    - name: dockersock
      path: /var/run

#- name: install-buildx-support
#  image: tonistiigi/binfmt
#  privileged: true
#  entrypoint:
#    - /usr/bin/binfmt
#  command:
#    - --install
#    - all
#  volumes:
#    - name: dockersock
#      path: /var/run

- name: set-tag-docker-prepare-stage-0-service
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
    - echo -n prepare-stage-0-latest > .tags
    - cat .tags

- name: docker-prepare-stage-0-service
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/honeycomb-video-streamer
    dockerfile: Prepare.stage-0.Dockerfile
    platforms: linux/amd64,linux/arm64
    cache_from: wildflowerschools/honeycomb-video-streamer:prepare-stage-0-latest

- name: set-tag-docker-prepare-service
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
    - echo -n prepare-v$DRONE_BUILD_NUMBER,prepare-latest > .tags
    - cat .tags

- name: docker-prepare-service
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/honeycomb-video-streamer
    dockerfile: Prepare.Dockerfile
    platforms: linux/amd64,linux/arm64
    cache_from: wildflowerschools/honeycomb-video-streamer:prepare-latest

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}