kind: pipeline
type: kubernetes
name: Build Streamer App
service_account_name: default

metadata:
  namespace: drone

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
- name: set-tag-docker-streamer-service
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
  - echo -n app-v$DRONE_BUILD_NUMBER,app-latest > .tags
  - cat .tags

- name: docker-streamer-service
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/honeycomb-video-streamer
    cache_from: wildflowerschools/honeycomb-video-streamer:app-latest

---
kind: pipeline
type: kubernetes
name: Build Streamer Prepare Service
service_account_name: default

metadata:
  namespace: drone

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
# This is apparently needed to make the multi-platform build work. Don't really know what's going on here.
- name: wait-for-docker-mount
  image: thegeeklab/drone-docker
  privileged: true
  commands:
    - timeout 60s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  volumes:
    - name: dockersock
      path: /var/run

- name: set-tag-docker-prepare-service
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
    - echo -n prepare-v$DRONE_BUILD_NUMBER,prepare-latest > .tags
    - cat .tags

- name: docker-prepare-service-amd64
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/honeycomb-video-streamer
    dockerfile: Prepare.Dockerfile
    platforms: linux/amd64
    cache_from:
      - type=registry\\,ref=wildflowerschools/honeycomb-video-streamer:prepare-cache-amd64
    cache_to: type=registry,ref=wildflowerschools/honeycomb-video-streamer:prepare-cache-amd64,mode=max

- name: docker-prepare-service-arm64
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/honeycomb-video-streamer
    dockerfile: Prepare.Dockerfile
    platforms: linux/arm64
    cache_from:
      - type=registry\\,ref=wildflowerschools/honeycomb-video-streamer:prepare-cache-arm64
    cache_to: type=registry,ref=wildflowerschools/honeycomb-video-streamer:prepare-cache-arm64,mode=max

services:
  - name: docker-service
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}