---
apiVersion: batch/v1
kind: Job
metadata:
  name: honeycomb-video-streamer-prepare-2021-05-28
  namespace: honeycomb
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: honeycomb-role
    spec:
      containers:
      - name: migrate
        image: wildflowerschools/honeycomb-video-streamer:prepare-latest
        envFrom:
          - secretRef:
              name: honeycomb-honeycomb_client-settings
          - secretRef:
              name: video-storage-honeycomb_client-settings
        env:
        - name: ENVIRONMENT_NAME
          value: greenbrier
        - name: OUTPUT_NAME
          value: 2021-05-28
        - name: START_TIME
          value: 2021-05-28T13:00
        - name: END_TIME
          value: 2021-05-28T21:00
        volumeMounts:
          - name: efs-pvc
            mountPath: "/data"
      restartPolicy: OnFailure
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs
  backoffLimit: 4

